### ISSUE TITLE
Delka festivalu

### ISSUE THREAD

**Issue by davidillichmannavitocz** [xillic00/iis-projekt#5]
asi bych zrusil celkem zbytecny sloupec Length jako delka festivalu a zmenil u festivalu slupec date na start_date a pridal sloupe end_date
@Frycak co ty na to?

**Comment by Frycak** [comment]
jj to dava smysl, budu ted upravovat v nejblizsi dobe trochu ten login & registraci, tak to tam muzu dodelat klidne.
